### ISSUE TITLE
Zip search error in Safari

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/townHallProject#101]
From techsupport email:

I'm using a Mac, OS 10.8.5, and my browser is an older version of Safari, 6.2.8.

When I go to your site, enter my zip code and click on Find A Town Hall, the page simply reloads but doesn't show any events. (I'm using my Arlington, MA and also Boston MA zip codes.)

I am trying 02476 and 02116.

Any help would be appreciated--thank you!

**Comment by meganrm** [comment]
it is possible this may be fixed by my recent PR, but I'm not sure.

**Comment by meganrm** [comment]
Fixed! Same issue as IE.
