### ISSUE TITLE
Change language on failed zip search

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/townHallProject#120]
From "That is not a real zip code" to "We could not find your zip code."

**Comment by meganrm** [comment]
I added two seperate error messages:
If someone doesn't enter 5 or 9 digits, then they get 
"Zip codes are 5 or 9 digits long."
If they enter 5 or 9 digits but is not in our database, they get:
"That zip code is not in our database, if you think this is an error please email us."

**Comment by nathanmwilliams** [comment]
Looks good. Thanks.

We've gotten a couple dozen irate "My zip code is REAL!" Lol...
