### ISSUE TITLE
Add more prominent email signup directly on home page

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/townHallProject#130]
Examples from NextGen and OFA below.

Question is how to incorporate the "opt-in to partner emails" box, which seems a little cluttered to have on front page. Maybe this initial signup takes the user here https://townhallproject.com/#join with the name/email already filled in? Then they can confirm the additional details?

![ofaisgnup](https://cloud.githubusercontent.com/assets/25805849/25102120/e9243df6-236b-11e7-8c86-08ac81add9e4.JPG)
![nextgenemailsignup](https://cloud.githubusercontent.com/assets/25805849/25102121/e92a5e7a-236b-11e7-8167-e8a323754d33.JPG)

**Comment by meganrm** [comment]
Here is what I am thinking. Add a fully functional signup to the main page for scollers. It would collect all the information we need (I didn't add the opt in to partner emails here).
![home_page](https://cloud.githubusercontent.com/assets/5170636/25733362/2455934e-310d-11e7-8fc7-899216940a90.jpg)

On the results page the form would be slightly different. It would store the zip in the background so they don't need to re-enter it, and if they are in more than one district it would ask which one they wanted (could be a dropdown instead of checkboxes). 
![results_page](https://cloud.githubusercontent.com/assets/5170636/25733363/24561c74-310d-11e7-9f3a-dbf4e8a086f4.jpg)

**Comment by pdvorchik** [comment]
Hm interesting @meganrm.   So we're not particularly interested in capturing phone numbers?

The one above the upcoming events looks relatively clean.  I worry the zip search one looks a bit overly busy and is difficult from a UX perspective.  I like the general ideal you're going for though, and am happy to jam on it for a bit and propose some tweaks tomorrow.

**Comment by meganrm** [comment]
Yeah, I agree about the clutter. 

And I'm not sure about the phone numbers. On the form now it is for 'not in the us?'. So maybe we only have it on the main page form? We should check with @nathanmwilliams.

**Comment by pdvorchik** [comment]
@meganrm here's where I'm at so far, lemme know what you think.  I've reworked the `input.input-lg` styling a bit so we could keep it consistent across the UX.  Still playing around a bit with the font-weight (ideally I'd love to get font family with different weights eventually).

Do you like the direction this is going?  The hope would be to reuse a lot on the right half of the zip code search pane, with the darker background of course.

## 1920x1080:
![image](https://cloud.githubusercontent.com/assets/4419203/25764148/853d0938-31b4-11e7-88e3-d74c0b910c0c.png)
![image](https://cloud.githubusercontent.com/assets/4419203/25764192/b326b95c-31b4-11e7-9775-98c774a1d872.png)
![image](https://cloud.githubusercontent.com/assets/4419203/25764988/9a0e8040-31b8-11e7-919c-c91120b1fb28.png)
![image](https://cloud.githubusercontent.com/assets/4419203/25765024/c68000b8-31b8-11e7-89f9-a931b8e71f53.png)




## Iphone 6:
![image](https://cloud.githubusercontent.com/assets/4419203/25764231/de27199e-31b4-11e7-96ff-1c1d96fe6c6f.png)
![image](https://cloud.githubusercontent.com/assets/4419203/25764247/f22d3bee-31b4-11e7-89ad-34b72b4e43d2.png)
![image](https://cloud.githubusercontent.com/assets/4419203/25765013/b5ec8e24-31b8-11e7-88f6-261867530cc2.png)

**Comment by nathanmwilliams** [comment]
Hi all.

Phone numbers are nice but less critical. In interest of keeping things clean and simple I'm fine without them. (I think if/when we launch an SMS notification feature we can do a phone number ask from our mailing list).

I'm digging the placement below the map. If/when somebody signs up, will it collapse/disappear? I'd love to not eat up that screen real estate for folks who are already signed up.

Lastly, how is the "Select your district" working. Will it prompt 2 if they are in a split zip code? Definitely don't want to ask people to scroll through 435 districts. More generally, I'm unsure if we want it at all. If it feels like an extra step and disincentivizes sign-up, I might rather they just get emails from two CDs.

Thanks for the great work!

**Comment by nathanmwilliams** [comment]
Also, can we do a different workflow for this? The current sign up page takes you to a "thanks for signing page" but for people who are on the front page I'd like to leave them where they landed. Could we instead generate a "thanks for signing up" email?

**Comment by pdvorchik** [comment]
@nathanmwilliams Yeah it'll only give you a choice of the districts that your zip code overlaps (so most of the time 2-3).

Both this form and the one on the map view will disappear once the user signs up.    And we'll definitely stay on the home page.

Playing with how the error messages look a bit more:
![image](https://cloud.githubusercontent.com/assets/4419203/25765929/95d18d9c-31bd-11e7-92c7-68ef15093014.png)


![image](https://cloud.githubusercontent.com/assets/4419203/25765992/e1239cf4-31bd-11e7-9f14-6b01228653b4.png)


![image](https://cloud.githubusercontent.com/assets/4419203/25765923/8d1c955c-31bd-11e7-933b-272c0b199061.png)
![image](https://cloud.githubusercontent.com/assets/4419203/25765926/8f27f148-31bd-11e7-8841-f48aa469d647.png)

**Comment by nathanmwilliams** [comment]
That all sounds great.

**Comment by pdvorchik** [comment]
If we want to just include all the districts then just lemme know (will need to talk to @meganrm to see what the database looks like, if we can store a collection).

Happy to keep it nice and clean if that's the preference.

**Comment by nathanmwilliams** [comment]
Instead of "opt in to partner emails" could we do "Opt in to updates from progressive partners." 

A little wordier but a little more specific. Hopefully conveys that we aren't selling their data to Pepsi and CitiBank...

**Comment by meganrm** [comment]
Re: select your district: 
If a user has searched for zip, and that zip has more than one district the form has "select your district if you know it", and the dropdown has the districts that map to that zip. If they don't choose a district, we just save their data with the zip. We shouldn't make this mandatory. 
If a user has selected a district on the map, or if there is only one district, instead of a dropdown that space just says "sign up for ${district}".
