### ISSUE TITLE
Add District Layer Makefile

### ISSUE THREAD

**Issue by DylanMoriarty** [townhallproject/townHallProject#137]
I'm currently creating the district layer via a makefile that eats a very high res district geojson and spits out a series of simplified geometries that are then merged to make the final layer we see. This process helps reduce the load time and makes the map look better at lower zoom levels. 

To add:

- [ ] Clean up makefile
- [ ] Add original geojson [119.6 MB] to S3 so no one has to download it when they're doing other work.
- [ ] Add a fetch for that file to the Makefile

**Comment by meganrm** [comment]
@DylanMoriarty what is the progress on this?

**Comment by meganrm** [comment]
@DylanMoriarty bumping again
