### ISSUE TITLE
Make sure all DC events have "DC Event" as their event type

### ISSUE THREAD

**Issue by meganrm** [townhallproject/townHallProject#146]

**Comment by meganrm** [comment]
@DylanMoriarty filter out using 'meetingType = DC Event' to filter these out. (I think there are some places were I was using state = DC'

**Comment by DylanMoriarty** [comment]
Solid. Looks like we're already filtering the district fill layers for `meetingType = DC Event`, so this just needed to be added to the filter for the point layer as well.

Thanks!

**Comment by meganrm** [comment]
And make sure they don't get returned on the search
