### ISSUE TITLE
Templates for "adopt-a-district" events

### ISSUE THREAD

**Issue by meganrm** [townhallproject/townHallProject#167]
@nathanmwilliams can you put the wording you think would be best for this?

**Comment by nathanmwilliams** [comment]
For email alerts?

**Comment by meganrm** [comment]
No for how they are displayed on the website. We talked about it before on slack, "District Rep:" and "Member of congress present: " or something similar.

**Comment by nathanmwilliams** [comment]
Ah, gotcha. How about this:

-Home district MoC (not present)
-Visiting MoC (will be present)

Possible to swap out "district" for "state" for Senator events?

**Comment by pdvorchik** [comment]
Closed by #170
