### ISSUE TITLE
Facebook / Eventbrite event scraping 

### ISSUE THREAD

**Issue by meganrm** [townhallproject/townHallProject#168]
Find events on facebook and eventbrite that look like town halls. 
Add them to the "pending events" list so they can be curated.

**Comment by pdvorchik** [comment]
@meganrm @nathanmwilliams 

Can someone with access to the official THP facebook setup a facebook app? Then I need the following info:  App Access Token (make sure the type is set to server!), app_id, and app_secret.

Also do we have an eventbrite account?  I need an api key for it.  If there's no account you guys want me to go ahead and make one?

Looks like a lot of code for this should actually be pretty simple.  Might not even need the SDK.  What terms do we want to search for besides "townhall", "town hall", and "town-hall"?

**Comment by nathanmwilliams** [comment]
We do not have an Eventbrite account so feel free to make one.

Simplest if I just invite you @pdvorchik to be an admin for our Facebook? 

For my twitter search I've found the following terms are useful:
town
hall
halls
forum
listening
coffee

Will we be able to make this search narrow to just official MOC facebook pages? Obviously those terms will bring in a ton of unrelated event otherwise.

**Comment by pdvorchik** [comment]
@nathanmwilliams Yeah if you want to add me as an admin I can do the rest.   My account is https://www.facebook.com/paolo.dvorchik

I can limit it to the offical MOC pages for facebook, but then won't we loose all the empty town halls and it wouldn't work with eventbrite?  Perhaps we can do two different kinds of searches, one that's loose with your list above, and then the pure "town hall" terms for the rest combined with being locked to events in the US?  

Either way, once I get the apps setup I can run some test searches and see what sorta noise we get,

**Comment by nathanmwilliams** [comment]
Cool. Yeah. Maybe let's see how noisy the broader search data is and then narrow from there as we see fit.

**Comment by nathanmwilliams** [comment]
Also, emailed you re: Facebook and a few other matters.

**Comment by pdvorchik** [comment]
@nathanmwilliams @meganrm Here are the first batch of results from eventbrite.  Let me know what you guys think.

There's a lot more data we can get from eventbrite too (description, if the even is free, if it's online, seating capacity) but I'm keeping it simple for demo purposes.

We get 18 hits using the terms: town hall senator, townhall senator, town hall congresswoman, townhall congresswoman, town hall congressman, townhall congressman:

Name: Senator Anderson's Parental Rights Town Hall, start in utc: 2017-08-12T17:00:00Z, url: https://www.eventbrite.com/e/senator-andersons-parental-rights-town-hall-tickets-36324089329?aff=ebapi
Name: Wilson Town Hall Meeting, start in utc: 2017-07-23T20:00:00Z, url: https://www.eventbrite.com/e/wilson-town-hall-meeting-tickets-35962830795?aff=ebapi
Name: Healthcare Town Hall, start in utc: 2017-08-03T23:30:00Z, url: https://www.eventbrite.com/e/healthcare-town-hall-tickets-36206336126?aff=ebapi
Name: Be The Solution: Youth & Family Immigration Town Hall , start in utc: 2017-09-10T17:00:00Z, url: https://www.eventbrite.com/e/be-the-solution-youth-family-immigration-town-hall-tickets-36276901188?aff=ebapi
Name: Damani for Alderman, start in utc: 2017-08-23T21:00:00Z, url: https://www.eventbrite.com/e/damani-for-alderman-tickets-36236474270?aff=ebapi
Name: We the People: a conversation about healthcare, start in utc: 2017-08-10T23:00:00Z, url: https://www.eventbrite.com/e/we-the-people-a-conversation-about-healthcare-registration-36200866767?aff=ebapi
Name: "Scenes and Songs from FANNIE LOU," Fannie Lou Hamer Honored at Yale Event, start in utc: 2017-10-01T19:00:00Z, url: https://www.eventbrite.com/e/scenes-and-songs-from-fannie-lou-fannie-lou-hamer-honored-at-yale-event-tickets-34394325353?aff=ebapi
Name: 2017 U.S-Nigeria Legislative & Executive Leadership Exchange Forum & Awards, start in utc: 2017-09-25T13:00:00Z, url: https://www.eventbrite.com/e/2017-us-nigeria-legislative-executive-leadership-exchange-forum-awards-registration-34724974333?aff=ebapi
Name: Indivisible WA 8th District: Town hall featuring Pramila Jayapal, start in utc: 2017-07-22T22:00:00Z, url: https://www.eventbrite.com/e/indivisible-wa-8th-district-town-hall-featuring-pramila-jayapal-tickets-35727257188?aff=ebapi
Name: Congressman Carbajal Town Hall, start in utc: 2017-08-24T00:00:00Z, url: https://www.eventbrite.com/e/congressman-carbajal-town-hall-tickets-35544275886?aff=ebapi
Name: Congressman Adam Smith Town Hall , start in utc: 2017-07-29T17:00:00Z, url: https://www.eventbrite.com/e/congressman-adam-smith-town-hall-tickets-36287664381?aff=ebapi
Name: Get Organized: Congressman Nadler's Community Town Hall, start in utc: 2017-08-01T22:00:00Z, url: https://www.eventbrite.com/e/get-organized-congressman-nadlers-community-town-hall-tickets-36211221739?aff=ebapi
Name: Veterans Town Hall with Rep. Lou Correa, start in utc: 2017-08-21T22:00:00Z, url: https://www.eventbrite.com/e/veterans-town-hall-with-rep-lou-correa-tickets-36284380559?aff=ebapi
Name: TOWN HALL: Entrepreneurship, Policy and Innovation in America , start in utc: 2017-08-04T01:00:00Z, url: https://www.eventbrite.com/e/town-hall-entrepreneurship-policy-and-innovation-in-america-tickets-36163543131?aff=ebapi
Name: Ca-48 Town Hall: Presented by Indivisible OC 48, start in utc: 2017-08-02T01:30:00Z, url: https://www.eventbrite.com/e/ca-48-town-hall-presented-by-indivisible-oc-48-tickets-35394649349?aff=ebapi
Name: Indivisible WA 8th District: Town hall featuring Pramila Jayapal, start in utc: 2017-07-22T22:00:00Z, url: https://www.eventbrite.com/e/indivisible-wa-8th-district-town-hall-featuring-pramila-jayapal-tickets-35727257188?aff=ebapi
Name: A Millennial Town Hall in Omaha, Hosted by Rep. Eric Swalwell (CA-15), start in utc: 2017-08-10T22:30:00Z, url: https://www.eventbrite.com/e/a-millennial-town-hall-in-omaha-hosted-by-rep-eric-swalwell-ca-15-tickets-35997357064?aff=ebapi
Name: North South Rail Link Salem MA Public Forum, start in utc: 2017-08-29T23:00:00Z, url: https://www.eventbrite.com/e/north-south-rail-link-salem-ma-public-forum-tickets-36432660067?aff=ebapi

We get another 46 if we include townhall representative, and town hall representative.  Though NB:  This list includes duplicates, and with them removed it'd be a few less.

Name: Free Community BBQ - The Colony, TX, start in utc: 2017-07-22T22:00:00Z, url: https://www.eventbrite.com/e/free-community-bbq-the-colony-tx-tickets-35893800323?aff=ebapi
Name: Florida Minority Enterprise Development Conference 2017, start in utc: 2017-08-15T12:00:00Z, url: https://www.eventbrite.com/e/florida-minority-enterprise-development-conference-2017-tickets-28171004232?aff=ebapi
Name: FITZROY TOWN HALL, start in utc: 2017-07-30T00:00:00Z, url: https://www.eventbrite.com.au/e/fitzroy-town-hall-tickets-36037494115?aff=ebapi
Name: Wilson Town Hall Meeting, start in utc: 2017-07-23T20:00:00Z, url: https://www.eventbrite.com/e/wilson-town-hall-meeting-tickets-35962830795?aff=ebapi
Name: Healthcare Town Hall, start in utc: 2017-08-03T23:30:00Z, url: https://www.eventbrite.com/e/healthcare-town-hall-tickets-36206336126?aff=ebapi
Name: Multicultural Town Hall, start in utc: 2017-07-22T16:00:00Z, url: https://www.eventbrite.com/e/multicultural-town-hall-tickets-35678905567?aff=ebapi
Name: Tri-County Town Hall, start in utc: 2017-08-18T01:00:00Z, url: https://www.eventbrite.com/e/tri-county-town-hall-registration-35970980170?aff=ebapi
Name: SICKLE CELL TOWN HALL MEETING, start in utc: 2017-09-22T23:00:00Z, url: https://www.eventbrite.com/e/sickle-cell-town-hall-meeting-tickets-35973950053?aff=ebapi
Name: TOWN HALL: Entrepreneurship, Policy and Innovation in America , start in utc: 2017-08-04T01:00:00Z, url: https://www.eventbrite.com/e/town-hall-entrepreneurship-policy-and-innovation-in-america-tickets-36163543131?aff=ebapi
Name: Pat Meehan Empty Swimsuit Town Hall , start in utc: 2017-07-29T22:00:00Z, url: https://www.eventbrite.com/e/pat-meehan-empty-swimsuit-town-hall-tickets-36051668511?aff=ebapi
Name: Be The Solution: Youth & Family Immigration Town Hall , start in utc: 2017-09-10T17:00:00Z, url: https://www.eventbrite.com/e/be-the-solution-youth-family-immigration-town-hall-tickets-36276901188?aff=ebapi
Name: Ca-48 Town Hall: Presented by Indivisible OC 48, start in utc: 2017-08-02T01:30:00Z, url: https://www.eventbrite.com/e/ca-48-town-hall-presented-by-indivisible-oc-48-tickets-35394649349?aff=ebapi
Name: Indivisible WA 8th District: Town hall featuring Pramila Jayapal, start in utc: 2017-07-22T22:00:00Z, url: https://www.eventbrite.com/e/indivisible-wa-8th-district-town-hall-featuring-pramila-jayapal-tickets-35727257188?aff=ebapi
Name: A Millennial Town Hall in Omaha, Hosted by Rep. Eric Swalwell (CA-15), start in utc: 2017-08-10T22:30:00Z, url: https://www.eventbrite.com/e/a-millennial-town-hall-in-omaha-hosted-by-rep-eric-swalwell-ca-15-tickets-35997357064?aff=ebapi
Name: Let's Talk About It: The Opioid Epidemic Town Hall Meeting, start in utc: 2017-08-03T21:30:00Z, url: https://www.eventbrite.com/e/lets-talk-about-it-the-opioid-epidemic-town-hall-meeting-tickets-35986605907?aff=ebapi
Name: Clay Book Production , start in utc: 2017-08-01T11:00:00Z, url: https://www.eventbrite.co.uk/e/clay-book-production-tickets-36221018040?aff=ebapi
Name: Clay Book Production, start in utc: 2017-08-01T13:00:00Z, url: https://www.eventbrite.co.uk/e/clay-book-production-tickets-36221097277?aff=ebapi
Name: Mayors' Megawatt Challenge Forum Nov 8th - Exhibition, start in utc: 2017-11-08T13:00:00Z, url: https://www.eventbrite.ca/e/mayors-megawatt-challenge-forum-nov-8th-exhibition-tickets-26611562901?aff=ebapi
Name: Mayors' Megawatt Challenge Forum Nov 8th - Industry, start in utc: 2017-11-08T13:00:00Z, url: https://www.eventbrite.ca/e/mayors-megawatt-challenge-forum-nov-8th-industry-tickets-31225862395?aff=ebapi
Name: Clay Book Production, start in utc: 2017-08-02T09:00:00Z, url: https://www.eventbrite.co.uk/e/clay-book-production-tickets-36221227667?aff=ebapi
Name: Clay Book Production, start in utc: 2017-08-01T15:00:00Z, url: https://www.eventbrite.co.uk/e/clay-book-production-tickets-36221123355?aff=ebapi
Name: Summer Wine & Cheese Fundraiser, start in utc: 2017-07-22T21:00:00Z, url: https://www.eventbrite.com/e/summer-wine-cheese-fundraiser-tickets-35787193459?aff=ebapi
Name: HBA 0.1K Micro Run, start in utc: 2017-09-17T19:00:00Z, url: https://www.eventbrite.com/e/hba-01k-micro-run-tickets-31492361501?aff=ebapi
Name: Small Business Conversations - Ballarat (VIC), start in utc: 2017-08-01T04:00:00Z, url: https://www.eventbrite.com.au/e/small-business-conversations-ballarat-vic-tickets-34055976342?aff=ebapi
Name: Back 2 School: Melbourne Spikers Trivia Night 2017, start in utc: 2017-08-05T09:00:00Z, url: https://www.eventbrite.com.au/e/back-2-school-melbourne-spikers-trivia-night-2017-tickets-35697434989?aff=ebapi
Name: We the People: a conversation about healthcare, start in utc: 2017-08-10T23:00:00Z, url: https://www.eventbrite.com/e/we-the-people-a-conversation-about-healthcare-registration-36200866767?aff=ebapi
Name: Edna Ryan Awards Night 20th Anniversary, start in utc: 2017-10-13T07:00:00Z, url: https://www.eventbrite.com.au/e/edna-ryan-awards-night-20th-anniversary-tickets-34402222975?aff=ebapi
Name: M-NJ Industry Summit Apprenticeships - Meeting the Workforce Challenge, start in utc: 2017-08-23T12:15:00Z, url: https://www.eventbrite.com/e/m-nj-industry-summit-apprenticeships-meeting-the-workforce-challenge-tickets-36069706463?aff=ebapi
Name: "I Am Of Cape Cod" Book Party, start in utc: 2017-08-01T22:30:00Z, url: https://www.eventbrite.com/e/i-am-of-cape-cod-book-party-tickets-36162681554?aff=ebapi
Name: Diverse Magazine 3rd Diversity & Inclusion Conference 2017, start in utc: 2017-10-18T07:00:00Z, url: https://www.eventbrite.co.uk/e/diverse-magazine-3rd-diversity-inclusion-conference-2017-tickets-31994986867?aff=ebapi
Name: The Public Bubble: Diversity in the Public Sector, start in utc: 2017-07-26T17:30:00Z, url: https://www.eventbrite.co.uk/e/the-public-bubble-diversity-in-the-public-sector-tickets-35726103738?aff=ebapi
Name: Damani for Alderman, start in utc: 2017-08-23T21:00:00Z, url: https://www.eventbrite.com/e/damani-for-alderman-tickets-36236474270?aff=ebapi
Name: Stronger Together - Celebrating women in business, start in utc: 2017-07-24T01:00:00Z, url: https://www.eventbrite.com.au/e/stronger-together-celebrating-women-in-business-tickets-35677417115?aff=ebapi
Name: Workshop: Building your personal brand, start in utc: 2017-07-29T04:00:00Z, url: https://www.eventbrite.com.au/e/workshop-building-your-personal-brand-tickets-35423284999?aff=ebapi
Name: Beyond the Bicycle Conference 2017, start in utc: 2017-11-07T09:30:00Z, url: https://www.eventbrite.co.uk/e/beyond-the-bicycle-conference-2017-tickets-34717241203?aff=ebapi
Name: 10th Annual Boston GreenFest Resilience, Race, and Equity EcoForum Registration, start in utc: 2017-08-13T14:00:00Z, url: https://www.eventbrite.com/e/10th-annual-boston-greenfest-resilience-race-and-equity-ecoforum-registration-tickets-36029396896?aff=ebapi
Name: The Tools for Making Successful Places - A Lead Event with West Dunbartonshire Council, start in utc: 2017-08-22T09:00:00Z, url: https://www.eventbrite.co.uk/e/the-tools-for-making-successful-places-a-lead-event-with-west-dunbartonshire-council-tickets-34820342582?aff=ebapi
Name: Sponsorship Opportunities: 2017 Professional Women in Advocacy Conference, start in utc: 2017-11-05T23:00:00Z, url: https://www.eventbrite.com/e/sponsorship-opportunities-2017-professional-women-in-advocacy-conference-registration-32095135414?aff=ebapi
Name: The Other Renewables Forum, start in utc: 2017-08-12T03:30:00Z, url: https://www.eventbrite.com.au/e/the-other-renewables-forum-tickets-36184993289?aff=ebapi
Name: 08 Days 07 nights Cairo, Alexandria, Aswan and Luxor including 03 nights Nile cruise Tour, start in utc: 2015-12-18T17:00:00Z, https://www.eventbrite.com/e/08-days-07-nights-cairo-alexandria-aswan-and-luxor-including-03-nights-nile-cruise-tour-tickets-20014645343?aff=ebapi
Name: "Scenes and Songs from FANNIE LOU," Fannie Lou Hamer Honored at Yale Event, start in utc: 2017-10-01T19:00:00Z, url: https://www.eventbrite.com/e/scenes-and-songs-from-fannie-lou-fannie-lou-hamer-honored-at-yale-event-tickets-34394325353?aff=ebapi
Name: Birjoo Mehta on the Vayus - 2017, start in utc: 2017-08-31T22:00:00Z, url: https://www.eventbrite.com/e/birjoo-mehta-on-the-vayus-2017-tickets-30231539348?aff=ebapi
Name: PASIC17 - Percussive Arts Society International Convention, start in utc: 2017-11-08T22:00:00Z, url: https://www.eventbrite.com/e/pasic17-percussive-arts-society-international-convention-tickets-33430137441?aff=ebapi
Name: Canada & Libraries as One, start in utc: 2017-09-14T14:00:00Z, url: https://www.eventbrite.ca/e/canada-libraries-as-one-tickets-34042165032?aff=ebapi
Name: Edinburgh Blues 'n' Rock Festival, start in utc: 2017-07-29T12:30:00Z, url: https://www.eventbrite.co.uk/e/edinburgh-blues-n-rock-festival-tickets-33658683027?aff=ebapi
Name: Indeterminate States: trans-cultural; trans-racial; trans-gender. , start in utc: 2018-08-02T14:00:00Z, url: https://www.eventbrite.com/e/indeterminate-states-trans-cultural-trans-racial-trans-gender-tickets-35830850037?aff=ebapi


I'll run some tests on facebook later.  Honestly it might be worth just sending in all the current MoC facebook events if there's not a ton.  But we'll see what the numbers look like.

**Comment by nathanmwilliams** [comment]
Looks like a good start. I think we need to add some additional search terms outside of "town hall" and "townhall" though, since many MOCs don't use that term. For instance, here's GK Butterfield's "community discussion"

https://www.eventbrite.com/e/forward-together-bertie-community-discussion-registration-36068841877?aff=es2

Also, is there a way to specifically search official accounts of MOCs?

**Comment by pdvorchik** [comment]
@nathanmwilliams Do we have a list of MoC's eventbrite accounts?  I'm not seeing one anywhere.  If we wanted the research team to put one together we could totally do that.

In that case, and in the case of facebook, let's look at the volume of events.  If it's not too high maybe we don't want to use keywords at all, just pass through everything?

**Comment by nathanmwilliams** [comment]
We could make this a project by a dedicated research team if valuable. In the lead up to August recess we probably don't have the humanpower to spare but could do this down the line.

That said, I don't think we'd exclusively want to use these. Because it would also be great to pull in Adopt-a-Districts and Empty Chairs, which won't be hosted by official MOC accounts (and also, unfortunately, also have a wide variety of nomenclature--"empty suit town halls" "ghost town halls" "with or without town halls," etc)

**Comment by pdvorchik** [comment]
Gotcha.  So let's get something up and running (facebook we can use the MoC events, eventbrite we can do the general searches).  Then once it's working we can start adding other stuff like the MoC eventbrite accounts later.

In the interim if there's MoC eventbrite events you already know of that aren't showing up, like the Butterfield one, lemme know and I can start making a list.

**Comment by nathanmwilliams** [comment]
Great. Agreed.

Another future feature that would be great is scraping actual MOC websites. Our vol researchers should be doing this of course but we never have 100% reliability and we occasionally miss events (ex: https://marshall.house.gov/media/press-releases/marshall-adds-dates-july-listening-tour). As you can see, these are all "town halls" but Marshall doesn't use the phrase once on the page.

**Comment by pdvorchik** [comment]
Yeah I'd love to be able to scrape all the things (tm).

**Comment by nathanmwilliams** [comment]
Awesome! Would it make sense to have a small research vol brigade assemble a spreadsheet with all the MOC web urls? Or maybe that's something ProPublic or GovTrack already has?

**Comment by pdvorchik** [comment]
We already have their normal web pages, but afaik no one has a list of the event calendar urls.  So yeah, I'd love to see a list of those (and also a list of the MoC eventbrite accounts).

I'll have to see what the calendars look like before I can start playing with scraping (it's more complicated that using the APIs, and we don't want tons of false positives).

I have the basics of the facebook code done.  Now to try eventbrite...then to test it all (kinda a pita as I don't have access to some of the endpoints but maybe @meganrm can help me once I get to that stage).
