### ISSUE TITLE
mbMAP: webGL detection 

### ISSUE THREAD

**Issue by meganrm** [townhallproject/townHallProject#178]
- [x] Check that a browser has webgl enabled
- [ ] if not, 
1. show a dismissable message (store dismissal in localstorage) that tells the person how to update their browser 
2. hide the map and the legend

**Comment by DylanMoriarty** [comment]
related: 
https://www.mapbox.com/mapbox-gl-js/api/#supported
https://www.mapbox.com/mapbox-gl-js/example/check-for-support/
