### ISSUE TITLE
Any way to update this text that appears in top google searches?

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/townHallProject#193]
![old meta](https://user-images.githubusercontent.com/25805849/29891780-2fca4a8c-8d81-11e7-81cd-64c7aa7a30d7.JPG)

**Comment by pdvorchik** [comment]
@nathanmwilliams Sure what text do you want it to be?

**Comment by nathanmwilliams** [comment]
Town Hall Project is a progressive,  a citizen-powered research and organizing project dedicated to holding lawmakers accountable via town hall meetings and other in-person engagement.

**Comment by pdvorchik** [comment]
Closed by #205.
