### ISSUE TITLE
Pat Toomey not appearing in auto-fill on Mac Chrome version of site

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/townHallProject#194]
Works for me on Windows Chrome. Researcher not able to get "Pat Toomey" to show up. 

System is OS X El Capitan Version 10.11.6. Up to date Chrome.

![screen shot 2017-09-01 at 5 07 19 pm](https://user-images.githubusercontent.com/25805849/29991229-785abbfc-8f38-11e7-9e4e-91f475cdc23d.png)

**Comment by meganrm** [comment]
Sorry, we should look for this again when there is another pat toomey event.
