### ISSUE TITLE
Add new emergency Graham-Cassidy banner

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/townHallProject#199]
TEXT

Congress is closer than ever to passing Trumpcare, with devastating effects for tens of millions of Americans. Call your Senators and Representative NOW and tell them to oppose this bill: 202-224-3121

**Comment by meganrm** [comment]
One idea:
<img width="1033" alt="screenshot 2017-09-19 10 01 25" src="https://user-images.githubusercontent.com/5170636/30605063-9edeffda-9d21-11e7-939c-fd13bb9d0aca.png">

**Comment by nathanmwilliams** [comment]
I like it. But could we make the font somewhat bigger, and the phone number even bigger?

**Comment by meganrm** [comment]
<img width="968" alt="screenshot 2017-09-19 19 17 40" src="https://user-images.githubusercontent.com/5170636/30623918-6227bc6e-9d6f-11e7-8de8-371af1b6781f.png">
<img width="496" alt="screenshot 2017-09-19 19 17 56" src="https://user-images.githubusercontent.com/5170636/30623917-62259286-9d6f-11e7-875e-87bf3c47006e.png">

**Comment by nathanmwilliams** [comment]
This looks solid. I take it the bottom is mobile? 

Only change I'd ask is punctuation at the end of "this bill." With the separated phone number it feels like the sentence is over and the number isn't connected.
