### ISSUE TITLE
David Kustoff in database?

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/townHallProject#203]
When I search for David Kustoff (TN-8) in the admin search function it gives a count of zero. And when I download Tennessee events he's not included. But he isn't on our Missing Members page.

**Comment by meganrm** [comment]
He is in the database, we dont have any events we've listed on the site for him, but he's also not on this list https://docs.google.com/spreadsheets/d/1_NxxTqSZHIvUNJIUs9XdAG9Kx2-Mt_Tx69WaYay9rAA/edit#gid=0
