### ISSUE TITLE
map icon for campaign events

### ISSUE THREAD

**Issue by meganrm** [townhallproject/townHallProject#214]

**Comment by DylanMoriarty** [comment]
I did some pondering on this last week. Do we want an altogether different icon, or maybe just recolor the 'in-person' one? The later seems to make more sense to me, as I struggle to think of an icon that represents "challenger" that isn't inappropriately boxing related.

**Comment by nathanmwilliams** [comment]
I'm okay with options that aren't a new icon, but the bigger issue isn't just "challenger" it's differentiating between when, say, Sen. Claire McCaskill holds a public town hall in her capacity as U.S. Senator (paid for with taxpayer dollars) and when candidate for Senate Claire McCaskill holds a town hall through her campaign (or through the local party, etc.). We want to be able to communicate clearly to our users when they are attending a true constituent forum and when they are at a campaign event.

**Comment by DylanMoriarty** [comment]
That sounds reasonable.

@meganrm is there a attribute already in the database to draw these icons by?

**Comment by meganrm** [comment]
i'm not sure what you mean... do you mean is there a value yet for the 'iconFlag'?

**Comment by DylanMoriarty** [comment]
<img width="324" alt="screenshot 2017-11-02 23 09 37" src="https://user-images.githubusercontent.com/9341928/32359182-6789ec1a-c022-11e7-963b-7bf5d9a7d20b.png">

Working example.

**Comment by meganrm** [comment]
Hey @DylanMoriarty.... so the iconFlag for these will be 'campaign'. Can you add this icon to the map?
