### ISSUE TITLE
Automatically add disclaimer to Candidate TH and Ticketed Event "Notes"

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/townHallProject#220]
Possible to automatically populate the Notes field with the following disclaimer?

_Town Hall Project lists this event and any third-party link as public information and not as an endorsement of a participating candidate, campaign, or party._

**Comment by meganrm** [comment]
@Alan-mag want to take a stab at this? you would add it to the switch statement I have for the meetingType selector. And make sure to clear it out if it gets changed to another meeting type.

**Comment by Alan-mag** [comment]
Yeah sure, I'll take a look

**Comment by Alan-mag** [comment]
Ok, is should be updated now

**Comment by nathanmwilliams** [comment]
Doesn't seem to be appearing now: I'll create an Issue in a sec, but looks like our legal disclaimer for campaign events isn't showing up: https://townhallproject.com/?eventId=-LkrmjuHhEqXi4gDWfvg
