### ISSUE TITLE
Karen Handel photo missing

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/townHallProject#237]
![handel](https://user-images.githubusercontent.com/25805849/34222557-d13b5888-e570-11e7-84be-0c5b1e3d8130.JPG)

**Comment by nathanmwilliams** [comment]
Same with Greg Gianforte.

**Comment by Alan-mag** [comment]
Are you still having this issue Nathan? They appear to be showing up on my end:
<img width="280" alt="gianforte" src="https://user-images.githubusercontent.com/3753457/34583072-175a1666-f14b-11e7-9185-6b850ef71073.png">
<img width="282" alt="khandel" src="https://user-images.githubusercontent.com/3753457/34583073-1773159e-f14b-11e7-8ed2-3d88ac012fd0.png">

**Comment by nathanmwilliams** [comment]
I see them now. Thanks!
