### ISSUE TITLE
No Events banner appearing for district with event

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/townHallProject#258]
Plus event itself is not appearing (apart from pin on map). 

Event in question here is a Campaign Town Hall. 

![incorrect no events](https://user-images.githubusercontent.com/25805849/34806127-47bf77b6-f636-11e7-9c2f-413abdaea19b.JPG)

**Comment by meganrm** [comment]
this would happen if the event doesnt' have a district, or the district is not formatted correctly

**Comment by nathanmwilliams** [comment]
Had to manually enter district since it's not an MOC but used standard convention here. "NC-07"

**Comment by meganrm** [comment]
i fixed those events but Ill update the form to work better with manually entered people
