### ISSUE TITLE
Update Swing Left Districts + Add Tax Votes to MOC Cards and MM page

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/townHallProject#281]
https://docs.google.com/spreadsheets/d/1l84CFphpp0hsGrUvSDBaOOhzQcpWZbkksw_6WyJhDgY/edit?usp=sharing

**Comment by meganrm** [comment]
I have updated the fields `swingLeft` and `taxBill`

**Comment by meganrm** [comment]
- [ ] add to missing members cards
- [ ] add to rep cards
- [ ] add both filter button to missing member pages
