### ISSUE TITLE
Eventbrite scraping error

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/townHallProject#288]
Listed this event as David Cicilline of Rhode Island: eb_42101095510

When it is actually David Price of North Carolina: https://www.eventbrite.com/e/town-hall-meeting-tickets-42101095510

**Comment by pdvorchik** [comment]
I'll look into this.  My guess is that this is a data issue, but I'll have to dig in to be sure.

**Comment by nathanmwilliams** [comment]
All the other EB events were fine. So not sure if there was something specifically weird about that one.

Also, I am an idiot and deleted it. Realize it might have been more helpful to leave it in there for you to investigage.

**Comment by pdvorchik** [comment]
Nah it's all good, easy enough to replicate.
