### ISSUE TITLE
Update glossary copy

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/townHallProject#302]
+ add definition as mouse-over text on event type bubble (see photo)

REVISED GLOSSARY

**Town Hall** - A forum where lawmakers give legislative updates and answer open questions from constituents.
**"Empty Chair" Town Hall** - A citizen-organized town hall held with or without the invited lawmaker.
**Adopt-A-District/State** - A citizen-organized town hall featuring a member of Congress from another district.
**Office Hours** - Opportunity to meet and question a lawmaker's staff. Usually held in district offices but sometimes are "mobile office hours."
**Campaign Town Hall** - A town hall organized by a candidate for office - whether an incumbent or challenger. (Town Hall Project includes these events as a public resource--not to endorse a particular candidate or campaign)
**Ticketed Event** - Paid events. Typically fundraisers. (Town Hall Project includes these events as a public resource--not to endorse a particular candidate or campaign)
**Tele-Town Hall**  - A town hall conducted by conference call or online.
**DC Event** - Event held in Washington D.C. when Congress is in session.

**Comment by meganrm** [comment]
@nathanmwilliams I dont see a photo attached to this, but you're saying you want this as a little tooltip? When you mouse over the event card or the table or both?

**Comment by nathanmwilliams** [comment]
Yeah, top priority is just updating the glossary on the main page and in the email alerts.

Total luxury is adding the definition as a tooltip on the event category bubble. 
![tooltip](https://user-images.githubusercontent.com/25805849/37295257-f14692ce-25d4-11e8-85f1-37632638c812.png)
