### ISSUE TITLE
Campaign event not showing as result from zip search

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/townHallProject#303]
Appears on map as icon but no event info appears.

Also, event is specific to WA-03 but hover text reads "Senate."

Event is -L5ylzRUb3FYb3RPtC2w

![multiple cand event](https://user-images.githubusercontent.com/25805849/36557316-ca5fac20-17bc-11e8-8ed2-6e42b2d48229.png)

**Comment by meganrm** [comment]
i think i fixed this
