### ISSUE TITLE
change copy on '#about' 'who we are'

### ISSUE THREAD

**Issue by meganrm** [townhallproject/townHallProject#318]
Juliana Amin - National Organizing Director - Before Town Hall Project, Juliana built organizing programs across the country over multiple cycles. Most recently she oversaw a team of more than 60 staff in Ohio for the Clinton campaign in 2016.

**Comment by meganrm** [comment]
@nathanmwilliams get robert's

**Comment by meganrm** [comment]
Replace Juliana with Jenita

**Comment by Alan-mag** [comment]
are we okay to close this now w/bio edits?
