### ISSUE TITLE
Download on certain MM posters seems broken

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/townHallProject#345]
E.G. Ted Cruz.

Also, do we really need two-step process of "Generate Flyer" and then "Download"? Can we just have a download button?

**Comment by meganrm** [comment]
@JacksonMaxfield

**Comment by JacksonMaxfield** [comment]
I really don't know what happened to this issue... I remember the issue clearly and was even experimenting with fixes but just now I went back through to get a list of any pages that images didn't load on, I loaded every MM page and all images loaded just fine, I also randomly downloaded about 1/10 of them and all downloaded fine. Ted Cruz download also works. Is it a mac vs windows thing maybe?

Browser and OS would help me narrow it down maybe? Also try it again and see if it was a github pages thing?

**Comment by nathanmwilliams** [comment]
Windows 7, Chrome. 

Ted Cruz won't download for me: https://jacksonmaxfield.github.io/flyer_gen/#/m=412573

**Comment by JacksonMaxfield** [comment]
Ahh I am on Firefox, will look into browser download mechanisms.

**Comment by JacksonMaxfield** [comment]
Are all the images loading though?

**Comment by nathanmwilliams** [comment]
Yeah, the image loads fine in the browser. Just nothing happens when I click "Download Flyer Image"

**Comment by JacksonMaxfield** [comment]
**Generate Flyer -> Download Flyer: Resolved**
Moved to a new download function that handles downloading really easily.

**Multi-Browser Support: Resolved**
Apparently Chrome doesn't like downloading pngs? I have changed the file format to jpeg and it works just fine now.

@nathanmwilliams @meganrm please test and close :)
