### ISSUE TITLE
newer MOC cards have no data

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/townHallProject#351]
![jones](https://user-images.githubusercontent.com/25805849/39389733-41b3678e-4a40-11e8-8378-95637b9b37b6.png)
![john curtis](https://user-images.githubusercontent.com/25805849/39389734-41cf77c6-4a40-11e8-8e47-9f32ebc675e5.png)

**Comment by meganrm** [comment]
propublica is pretty slow to update these fields. We are pulling from them....but i'm afraid it's still just faster for us to manually update some of this data.

**Comment by nathanmwilliams** [comment]
How can I help manually update? Doug Jones has been in office since Jan. 3.

**Comment by meganrm** [comment]
https://townhalladmin.herokuapp.com/#moc-editor

**Comment by meganrm** [comment]
this has been updated to include 'next_election' as an editable field https://townhalladmin.herokuapp.com/#moc-editor

**Comment by nathanmwilliams** [comment]
Can we manually add Office # and the other stuff on the cards?

**Comment by meganrm** [comment]
I've added social and contact info to the form
