### ISSUE TITLE
Do Your Job Banner

### ISSUE THREAD

**Issue by pdvorchik** [townhallproject/townHallProject#372]
**User story**
Website visitors want to be made away of the DYJ/Pledge site.

**Implementation**
Make a small/streamlined banner near the top of the page that links to the pledge site.

**Comment by pdvorchik** [comment]
@nathanmwilliams Do we have text for this?

**Comment by nathanmwilliams** [comment]
I can write some. This is for the banner on townhallproject.com?

**Comment by pdvorchik** [comment]
Yup!
