### ISSUE TITLE
Add 2018 Awards graphic banner

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/townHallProject#400]
Graphic here.
![Uploading 2018RoundUp.png…]()

**Comment by meganrm** [comment]
this never uploaded, too big i think

**Comment by meganrm** [comment]
@nathanmwilliams  can you upload this again

**Comment by nathanmwilliams** [comment]
![2018roundup](https://user-images.githubusercontent.com/25805849/51700253-84497080-1fc3-11e9-8457-4614944cf182.png)
