### ISSUE TITLE
Add "THP 2-year anniversary banner"

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/townHallProject#425]
"Town Hall Project is two years old! Thank you for your support. Take a look back at everything we've accomplished together in the last year. "

**Comment by meganrm** [comment]
Do you want this across the top of the site? And then a link to open the image?

**Comment by nathanmwilliams** [comment]
Yep!

**Comment by nathanmwilliams** [comment]
Plus a static url for the image that we can link to directly from social / email.
