### ISSUE TITLE
"ADA Accessible" appears to have replaced the Add to Calendar button

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/townHallProject#440]
Possible to move ADA to center and keep Calendar?
![adacalendarerror](https://user-images.githubusercontent.com/25805849/52906085-21ca4580-31fa-11e9-87b0-50d64dbe10d6.png)

**Comment by Alan-mag** [comment]
spacing issue:
![image](https://user-images.githubusercontent.com/3753457/53112566-5e48ba80-34f4-11e9-81e4-151d70c1022f.png)

I'll look into
