### ISSUE TITLE
Title on "Community Event" no longer displaying

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/townHallProject#469]
![community](https://user-images.githubusercontent.com/25805849/56002547-b93a9a80-5c77-11e9-81ff-dcd7f7d3fb6c.png)
![Empty event](https://user-images.githubusercontent.com/25805849/56002548-b93a9a80-5c77-11e9-89f8-1636cfc6ef1b.png)

**Comment by meganrm** [comment]
is this a pending event?

**Comment by nathanmwilliams** [comment]
No, I was just showing that it does have a title in #All-Events-Page

**Comment by nathanmwilliams** [comment]
https://townhallproject.com/?eventId=-LaHzuUtEdhGem4f4SAZ
