### ISSUE TITLE
Remove broken Indivisible link on About Page

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/townHallProject#474]
Also remove NextGen partner sentence. 
![About update](https://user-images.githubusercontent.com/25805849/56381805-b2a5a900-61ca-11e9-8dd0-54826e2028cf.png)

**Comment by nathanmwilliams** [comment]
https://townhallproject.com/#about

REMOVE

_For more, we recommend:
Indivisible's Town Hall strategy resources_

AND

_We are also proud to partner with NextGen America and other progressive allies in supporting grassroots action to hold our elected officials accountable._

**Comment by nathanmwilliams** [comment]
Dead link is still up. Bumping for removal as soon as is convenient.

**Comment by serengetisunset** [comment]
@nathanmwilliams This link isn't dead as of 2:35am, May 7, Seattle time (it leads to a live page on Indivisible's website). Do you still want this link deleted?

**Comment by nathanmwilliams** [comment]
Hmm. Good question. Let me check with them to see if they will keep that link up (it was done for a few weeks).

In the meantime, can you remove the sentence at the bottom of the OUR SUPPORTERS section:

_We are also proud to partner with NextGen America and other progressive allies in supporting grassroots action to hold our elected officials accountable._

**Comment by nathanmwilliams** [comment]
UPDATE: Talked to the folks at Indivisible. The link issue was that we are linking to "www" -- they've been having DNS issues off and on.

Can you change to link to the more reliable: https://indivisible.org/resource/town-hall-guide

**Comment by serengetisunset** [comment]
@nathanmwilliams We also have a couple of other links to Indivisible's `www` domain on the website: https://www.indivisibleguide.com/act-locally/ (this one, specifically). Do you want me to change those out to the `.org` one as well?

**Comment by nathanmwilliams** [comment]
Yeah, if those .org links work, that'd be great. Thank you!

**Comment by serengetisunset** [comment]
@nathanmwilliams I'm going to switch https://www.indivisibleguide.com/act-locally/ over to: https://indivisible.org/groups. This is the link that the original URL is currently redirecting to. Please let me know if this is incorrect.
