### ISSUE TITLE
create icons for new states

### ISSUE THREAD

**Issue by meganrm** [townhallproject/townHallProject#478]

**Comment by nathanmwilliams** [comment]
NEVADA

-The sagebrush part of the state flag logo? 
https://upload.wikimedia.org/wikipedia/commons/f/f1/Flag_of_Nevada.svg
https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDQ-53a_FT5vUUu7FsB1GCUOcVSoxIOr3OU8MkME6PVeOZ0Tbo


MICHIGAN

-The two deer from the flag? (Anything more iconic than this you or the Michigander you co-habit with can think of, Jimmy? 

https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Coat_of_arms_of_Michigan.svg/800px-Coat_of_arms_of_Michigan.svg.png


MAINE

-Lighthouse https://cdn.dribbble.com/users/1653919/screenshots/3686281/optimized-um_lighthouse.001.jpeg


MARYLAND

Chesapeake crab? (E.g. https://images-na.ssl-images-amazon.com/images/I/71FPTnqjndL._SX425_.jpg) --> not that color combo



PENNSYLVANIA

Liberty Bell image, option 2


FLORIDA

Alligator, natch

http://clipart-library.com/images/6iroyKgAT.jpg

**Comment by meganrm** [comment]
<img width="1158" alt="Screenshot 2019-04-29 19 06 14" src="https://user-images.githubusercontent.com/5170636/56937510-ef6a7d80-6ab1-11e9-8ae3-05dde2e6b551.png">
<img width="1257" alt="Screenshot 2019-04-29 19 09 08" src="https://user-images.githubusercontent.com/5170636/56937881-e11d6100-6ab3-11e9-9e2e-e4a4fa610d25.png">
<img width="1280" alt="Screenshot 2019-04-29 19 11 57" src="https://user-images.githubusercontent.com/5170636/56937882-e1b5f780-6ab3-11e9-9d2e-694989c847c2.png">
<img width="1236" alt="Screenshot 2019-04-29 19 20 31" src="https://user-images.githubusercontent.com/5170636/56937883-e1b5f780-6ab3-11e9-8a94-98611205f042.png">

**Comment by nathanmwilliams** [comment]
These are great! Only note is I think the bell on PA could be a little smaller. And maybe a different, cooler color?

**Comment by meganrm** [comment]
i also thought the gator was hard to see. I was going to tried a filled in version

**Comment by nathanmwilliams** [comment]
Bumping Maryland, which is currently logo-less.
