### ISSUE TITLE
Update Table options for State Sites

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/townHallProject#505]
Table content is currently not a good fit for state legislatures.

Amend to the following:

**MEMBER** [remove, not needed on the typically short state tables]

**STATE** [remove, irrelevant here]

**EVENT TYPE** [remove "DC Event," add "Other"]

**SORT** [remove "by State," add "by Name"]

Also, for state sites please have the default table setting to display ALL events. 

![table sorting](https://user-images.githubusercontent.com/25805849/59288743-5048b200-8c29-11e9-809f-5aa0dbde0c13.png)

**Comment by JacksonMaxfield** [comment]
For `By Name` do you mean `By Candidate Name`?

**Comment by JacksonMaxfield** [comment]
And specifically `By Candidate Last Name`?

**Comment by nathanmwilliams** [comment]
Yeah, Candidate/Lawmaker Last Name. Sort alphabetically.
