### ISSUE TITLE
Re-launch Missing Member Page for 2019

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/townHallProject#523]
-Hopefully by last week of July.

-Same interface design as 2017-2018 is fine.

-Ability to manually edit "Missing Member" status on Admin 2.0 will be critical. 

-Auto-removing Missing Members if when a "town hall" event is added to the database for the timespan of this Congress (Jan 1, 2019 - Dec 31 2020)

**Comment by nathanmwilliams** [comment]
Missing Member count is currently too high (as of 7/24).

E.g. Scott Peters had held a town hall in 2019. But he's appearing as an MM on the chart.
![scott peters](https://user-images.githubusercontent.com/25805849/61831639-44a0fb80-ae23-11e9-9c27-2c2dbb50df9a.png)
![scott peters](https://user-images.githubusercontent.com/25805849/61831641-44a0fb80-ae23-11e9-852d-8238461ab698.JPG)

**Comment by meganrm** [comment]
fixed scott peters in particular (it wasn't including the eventbrite counts because they didn't have a user associated with them. I fixed that. Let me know if you come across more

**Comment by nathanmwilliams** [comment]
Jared Huffman
Diana DeGette
Scott Tipton
![degette](https://user-images.githubusercontent.com/25805849/61832970-b8dd9e00-ae27-11e9-9a0b-da4ca29d6c97.JPG)

**Comment by nathanmwilliams** [comment]
Last need is making sure the poster downloads work (or removing the poster downloads for now--they are fun but not critical for this launch)
