### ISSUE TITLE
Close gunsafetytownhalls.org for the season

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/townHallProject#553]
-Stop populating with new events
-banner in front of map to read "Check back soon for more from the gun safety coalition."

**Comment by meganrm** [comment]
A few questions: 
Do you want that wording instead of the current title, or below it? Should I remove the rest of the text?

For the events: should it just show nothing or keep showing events in the past?

**Comment by nathanmwilliams** [comment]
Short answer: whatever is easiest for you since there won't be a ton of organic traffic to this url for now.

Long answer:

My ideal version of this is just freezing the whole site, including whatever events are displayed, and then graying out the whole thing with the Away message in a box on top of it (akin to what we did for Maine but for the whole site)
