### ISSUE TITLE
Links in email do not link to events

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/townHallProject#555]
Please make links in our email alerts link to the specific event NOT just to townhallproject.com

E.g 
![link error](https://user-images.githubusercontent.com/25805849/65184781-17378f00-da1b-11e9-941d-b19f5a39881b.png)

**Comment by meganrm** [comment]
These do link to the event, i just named the link the same.

**Comment by nathanmwilliams** [comment]
For me it goes to the front page of townhallproject.com. And for multiple reports from our partners.

**Comment by meganrm** [comment]
views/eventView.js

This is the function that needs adjustment (line 320): 
  function checkEventParam() {
    var eventId = urlParamsHandler.getUrlParameter('eventId');
    if (eventId) {
      firebasedb.ref('/townHalls/' + eventId).once('value').then(function(snapshot) {
        if (snapshot.val()) {
          var townhall = new TownHall(snapshot.val());
          townhall.makeFormattedMember();
          eventHandler.populateEventModal(townhall);
          $('.event-modal').modal('show');
        }
      });
    }
  }

**Comment by meganrm** [comment]
example ref : `state_townhalls/AZ/-Lbze3XGSfqRiAoqnYms`
ie: townhallproject.com/?eventId=-Lbze3XGSfqRiAoqnYms&state=AZ
should take you to the firebasedb.ref( `state_townhalls/AZ/-Lbze3XGSfqRiAoqnYms`)
