### ISSUE TITLE
IMPEACHMENT: Text bleed over on MOC cards with longer names

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/townHallProject#587]
![text over](https://user-images.githubusercontent.com/25805849/67794224-8bf9e200-fa39-11e9-8bda-046d7721eb5c.png)

**Comment by Alan-mag** [comment]
![image](https://user-images.githubusercontent.com/3753457/73902077-8cc8be00-4849-11ea-8884-6544debf1aba.png)

This issue should be addressed as we roll out MOC cards across the site

**Comment by Alan-mag** [comment]
For main table these changes have gone out
