### ISSUE TITLE
Updated automated email copy

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/townHallProject#626]
Updated copy: 

https://docs.google.com/document/d/1nNLVZtu_XM8MZp3LZ1yof2txTg-fXuMcbJN5RacSHig/edit?usp=sharing

**Comment by meganrm** [comment]
do you want this to now say you at the end again instead of Jenita?

**Comment by nathanmwilliams** [comment]
Ah, good thought. Can we go with Zoë?

**Comment by meganrm** [comment]
sure

**Comment by meganrm** [comment]
do you know if there are other changes within this doc?

**Comment by nathanmwilliams** [comment]
I think it's good otherwise. There's one issue where my Bolding is a little sloppy but that's probably self-evident.
