### ISSUE TITLE
Search by State doesn't seem to be working

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/townHallProject#643]
I tried both "New Hampshire" and "NH"
![search by state](https://user-images.githubusercontent.com/25805849/73690229-be445c80-4684-11ea-995f-6ed8e08358ac.JPG)

**Comment by meganrm** [comment]
I just tried and it seems to work. It's supposed to do a type ahead for you and populate the drop down. 'NH' will not work.
