### ISSUE TITLE
ADA Symbol overlapping text on main table

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/townHallProject#645]
![ADA symbol](https://user-images.githubusercontent.com/25805849/73872792-3a65ae00-4805-11ea-97f4-17ede8d0cdf8.png)

**Comment by Alan-mag** [comment]
Hey Nathan, would you mind providing a few more details on this issue?

I'm just curious which browser you're using, and at what width your screen is?  I'm having a tricky time reproducing this issue on my end. thanks!

**Comment by nathanmwilliams** [comment]
Sure thing.

It's Chrome, in the most recent update as far as I can tell.

Not sure how to gauge the exact dimensions of the browser, but it's full maximized on a 1080x1920 display.
