### ISSUE TITLE
Certain expired events not rolling off main table

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/townHallProject#649]
E.g. Image taken 2/17

![roll off](https://user-images.githubusercontent.com/25805849/74674442-353e2280-5166-11ea-957b-a477da2c7f10.png)

**Comment by meganrm** [comment]
the server that was running this code crashed. It is running again and should pull events off the site tonight at midnight. Let me know if it doesnt

**Comment by nathanmwilliams** [comment]
*praise hands*
