### ISSUE TITLE
Store zipcode and indiviual events searches as query param

### ISSUE THREAD

**Issue by pdvorchik** [townhallproject/townHallProject#66]
It'd be nice to let people link to searches, so if friends are talking about going to an even together they cna share the link.  Or you can bookmark the view for events in your area.

- [x] On search store the zip as a query param
- [x] Run the search on load if query param is present 
- [x] query param for individual events

**Comment by pdvorchik** [comment]
@meganrm @nathanmwilliams 

How do we want to show individual events?  I'd like to figure out how we want to architect the UX so we can ensure it'll be consistent as we expand features in the future.

**Option 1: Modals**
Advantages:  We could use it on the home page (triggered by the town hall table) and eventually on the MoC pages once we get them done.  It's clean, reusable, and allows people to easily get back to looking at the other info.
Disadvantages:  Once we start using modals for content instead of choices it tends to spitball.  I don't really want to see them used for MoC pages, etc, so we'd have to be vigilant,

**Option 2: New page**
Advantages:  It's explicitly clear that this page is for this event and nothing else.   It also gives us more room for content than a modal does...but I don't know if we have enough info to actually fill up an entire page.  It might be more inline with how we'll eventually do the MoC pages.
Disadvantages:  There won't be as clear of a way for them to get back to looking at other town halls.  We'll have to flesh out our routing solution more. 

**Option 3:  Use the bootstrap collapse boxes in the event table**
Advantages:  We were already talking about using these for the event table.  This way every event would have one and the UX would be consistent.
Disadvantages:  The table would be doing double duty and I think that could be pretty confusing to users.  I also don't like the idea of cramming a bunch of info (if we want to do maps/directions etc) in such a small space.  Seems like it'd be cramped and also slow down the page if they opened a bunch.

My vote is to go with the modals, but wanted to throw it out there in case you guys had feedback.

**Comment by nathanmwilliams** [comment]
Would we be able to link to the modals with a static link? Ultimately the goal is to be able to have a partner org send people directly to an event on our page.

**Comment by pdvorchik** [comment]
@nathanmwilliams yup, all three solutions would allow for static links.

**Comment by nathanmwilliams** [comment]
Cool. Then I defer to your and Megan's judgment on the best route. Modal
sounds good but I admittedly have only a loose understanding of all the
implications.

**Comment by pdvorchik** [comment]
Notes to self, things left to do:

- [ ] Fix queryparam string when there's no params left
- [ ] Clean up mobile views
- [ ] Fix calendar, and make it look reasonable on mobile
- [ ] Shorten dates on mobile
- [ ] stoppropigation on details link click to prevent collapse
