### ISSUE TITLE
Map District Interactions

### ISSUE THREAD

**Issue by DylanMoriarty** [townhallproject/townHallProject#68]
### To be Determined

- [x] District choropleth coloring
- [x] Styling

---

Currently have these added in. When you click on a district it highlights and the map pan & zooms over to it.

![district-click](https://cloud.githubusercontent.com/assets/9341928/23341428/915066ae-fc15-11e6-85f3-002ee2750b6c.gif)

We'd previously discussed basing the fill colors based on:

- no events
- telephone only
- in-person

but after looking at the above map, I think it might make more sense to use the fill color to indicate whether a district has a Town Hall opportunity for a _local_ rep or a _senate_ rep. That way it's more clear from looking at the map why places like Texas are all filled in. Discriminating between telephone & in-person might be better handled in [the icons themselves](https://github.com/meganrm/townHallProject/issues/67) imo.

### To do

- [ ] Create a makefile to allow easy repliaction of the mbtiles used to make the district layer from a Shape File
- [x] Filter the fill color based on Senate vs. District
- [x] Tweak the style to match the Town Hall style guide

**Comment by pdvorchik** [comment]
I'm wary of going with yellow, orange, or green because it doesn't match the styleguide and this sorta thing is how we loose visual consistency.

Something along the lines of 
None: #f7fbff
Senate: #9ecae1
House: #08306b

Would fit closer to our styleguide though it's still not using exact values (we don't have a full secondary and tertiary pallet afaik).

**Comment by DylanMoriarty** [comment]
The TownHall style's colors don't translate the best onto the map directly. I tried a few combinations, but ultimately I think doing some light blue is the most pleasant while still #onbrand.

<img width="812" alt="screenshot 2017-04-17 17 55 04" src="https://cloud.githubusercontent.com/assets/9341928/25106383/3030845e-2397-11e7-87ab-5a475869486a.png">

As you can see I also chose to use a stripped pattern for the Senate races, as that makes it more obvious where there are both local _and_ senate races. I toyed with outlining the state, but I don't like using separate symbology for representing things that are in the same categorical bin.

Kept the green for the call icon because there aren't too many of them and it still pops. Tried it with it being a red, but I think that triggers the 'oh this is republican / democrat thing' warning flag in the back of my mind.

**Comment by nathanmwilliams** [comment]
I like the stripes and the green for the call. 

Blue generally seems like a good call. Ultimately might be good to see the blues we have here (incl. water) in context with the rest of the blues on the site that will be surrounding the map.
