### ISSUE TITLE
Add 2020 Awards Graphic

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/townHallProject#732]
And replace with "2020 in Review" --> linking to 2020 End of Year Report. 

https://docs.google.com/document/d/e/2PACX-1vSwH66OWsI_TNeRCLUkfdbyEFZkLXi3kIqLoSPbX0k2DzI8bxqKi911UV7AwhY6XjjuosyMT8Rv-gX4/pub

**Comment by meganrm** [comment]
do we have an infographic for the 2020 awards?

**Comment by nathanmwilliams** [comment]
Ashlee is working on the Awards graphic but we don't have that yet. There won't be a Report Infographic this time (since we have so few stats).

**Comment by nathanmwilliams** [comment]
![2020-THP-Awards](https://user-images.githubusercontent.com/25805849/103954669-91e95980-50f9-11eb-8a51-532152a65065.png)

**Comment by meganrm** [comment]
I think i still haven't gotten the full res version of this
