### ISSUE TITLE
For new card layout on home page, can we add a "notes" button

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/townHallProject#75]
Not intuitive that clicking on the event should give you notes. Maybe just under the Town Hall (etc.) oval?

**Comment by pdvorchik** [comment]
With a button the popover interface gets a bit odd.

What do you guys think about using something like https://v4-alpha.getbootstrap.com/components/collapse/ instead?  It's clean and gets out of the way when it's not being used.  Would also give us more realestate for other info (groups going, rep info, map, whatever) without cluttering up the UI.

**Comment by meganrm** [comment]
Yeah I was thinking that too.... I think it's a good idea. I was also thinking that on the results page (after a search) the "table" could just replace the cards, instead of the two different views. Especially if we find a clean way to fit all the info on them.

**Comment by meganrm** [comment]
I've also added the MOC table to the database. To get it the data its firebasedb/MOCs/lastname_firstname  I did this for autopopulatimg the entry form but could be useful in other places.
