### ISSUE TITLE
Edit failed zip search copy

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/townHallProject#79]
Can we alter the "That's not a real zip code" error message to "We couldn't find your zip code! Right now we are only able to search by 5-digit zip so please try yours again." Or something along those lines.

**Comment by meganrm** [comment]
for a quickfix: we can do the proximity lookup by 5 digits (split on dash), but do the rep search with the full zip. we can also add a geocode lookup.

**Comment by nathanmwilliams** [comment]
Just so I understand: could we still do the rep search with 5-digit zip,
with the current "your zip is in two districts" response for those folks?
Most people don't know their 9-digit zip offhand so I wouldn't want to
limit them.

**Comment by pdvorchik** [comment]
Absolutely.  Splitting them is a non issue.

**Comment by meganrm** [comment]
Pull request #97
