### ISSUE TITLE
Streamlined "About" copy

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/townHallProject#82]
Can we change the main About copy at top to the more streamlined copy here:

Town Hall Project empowers constituents across the country to have face-to-face conversations with their elected representatives. We are campaign veterans and first time volunteers. We come from a diversity of backgrounds and live across the country. We share progressive values and believe strongly in civic engagement. We research every district and state for public events with members of Congress. Then we share our findings to promote participation in the democratic process. 

This movement is diverse, open source, and powered by citizens. We are proud to be a part of it.

**Comment by meganrm** [comment]
merged but not deployed yet.

**Comment by meganrm** [comment]
deployed
