### ISSUE TITLE
Sort by date errors

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/townHallProject#83]
Some events appear out of date order:

Going from 3/13 events, then:

thomas garrett on 3/9
thomas garrett on 3/31
rob wittman on 3/18
susan bonamici on 4/15

and then back to normal with marc veasey on 3/16

**Comment by jostrow** [comment]
Hi @nathanmwilliams -- I assume you're talking about the main "Upcoming Events" table.

When I first visit the site, it appears the table is sorted "by state" by default, so the dates should appear out of sequence.  A couple observations, then maybe you can guide me in the right direction on how you'd like to handle it (+ @meganrm ):

1) "Sort by state" actually appears to be sorting more specifically by district.  Districts are grouped together, so the dates can still be out-of-sequence within a given state.

2) When a user explicitly "sorts by date," it appears to work fine.  There is some weirdness with how the recurring events are handled (e.g. "every 3rd Tuesday"), but I'll leave that for a separate issue.

So, what to do?  This being my first comment, I'd appreciate some direction.  :]

a) Begin sorting "by date" by default, until the user changes the sort

b) Add an additional sort option, "By District," which would behave how the existing "By State" sorting works.  Change "By State" to actually sort by state, unlike how it works today.

c) Make sure any changes are applied consistently to the detailed events page (what you see after entering a zip code).  Those appear to be funky as well (maybe driven by the same code-- not sure yet).

Any combination of the above?  Thanks!

**Comment by nathanmwilliams** [comment]
Yeah, was referring to Upcoming Events on the main page.

Looks like they are in correct date order now.  Not sure if that's something @meganrm has fixed, or if it was an issue with how our events were originally formatted on the google doc side (which we are retiring soon, thankfully). 

I like "by date" as a default. Not sure a "by district" sort is necessary. I think search by district would be great, but can't see who would need a district-specific sort. Correct sorting by state would also be great.

Will defer to the two of you on how to proceed. Thanks!

**Comment by meganrm** [comment]
In general this issue has been resolved, but it's still open because of number 2 below. 
@nathanmwilliams previously you asked the table to load by default in order by State, but we can change that to Date. 

1. https://github.com/townhallproject/townHallProject/blob/development/scripts/views/mapView.js,

 change line 401 var townHallsFB = firebase.database().ref('/townHalls/').orderByChild('State');
to .orderByChild('DateObj'). 

2. Our sort function doesn't have an exception for if an event doesn't have the attribute being sorted (which would happen with dates because some events don't have dateObjs.

**Comment by nathanmwilliams** [comment]
Sorry to contradict myself. I think the default sort by Date is now best, with the default setting of only Town Halls (and maybe Empty Chair Town Halls as well?)

**Comment by meganrm** [comment]
no problem... I made that a separate issue.

**Comment by nathanmwilliams** [comment]
Re: #2, which events don't have dates? Repeating events?

**Comment by meganrm** [comment]
@nathanmwilliams yeah, repeating events. They don't have a value we can sort on.

**Comment by nathanmwilliams** [comment]
Possible to just push them to the bottom of the list? Seems like few people
will search for all Office Hours and then want to seach by Date. Would
mostly be interested in geography or specific reps.

**Comment by pdvorchik** [comment]
Yeah that's definitely doable.

**Comment by meganrm** [comment]
@jostrow are you going to work on this? It's something that breaks easily if there are any issues with dates, and we should be handling events without dates in the sort better.
