### ISSUE TITLE
Submit a town hall form

### ISSUE THREAD

**Issue by pdvorchik** [townhallproject/townHallProject#84]
We'd like to get away from embeding the google form and instead make our own.

USER STORIES:
- As an end user I want to be able to submit new townhalls via the site.  I want this process to be as quick and painless as possible.

- As a data entry volunteer I want the data submitted to be as sanitized as possible to prevent extra work.

IMPLEMENTATION:
- [x] Create formset with bootstrap
- [x] Create validation for email, required fields, and dates
- [x] On submission post it to firebase
- [x] Standardize rep lookup (either typeahead or drop down populated by zipcode lookup).

BONUS:
- [x] Auto populate city and state from zipcode using http://www.zippopotam.us/
- [x] Use a datepicker like https://bootstrap-datepicker.readthedocs.io/en/latest/

**Comment by meganrm** [comment]
It's posting directly to firebase not a Google doc.

**Comment by pdvorchik** [comment]
Even better.  Ticket updated.

**Comment by meganrm** [comment]
https://townhalladmin.herokuapp.com/#new-page <-- this is where the version I'm testing lives. There's no submit yet, so it doesn't do anything, but it will be working tonight.
