### ISSUE TITLE
Clean up MoC Cards

### ISSUE THREAD

**Issue by pdvorchik** [townhallproject/townHallProject#86]
USER STORIES:
- As an end user I want to be able to see all pertinent info in one single view without having to scroll.

IMPLEMENTATION:
- [x] Shrink footprint of these cards.  Treat space as a premium.
- [x] Ensure mobile views of the cards look okay
- [x] Switch all online contact links to fa icons
- [x] Remove the office address until we have an option to get local offices.

**Comment by nathanmwilliams** [comment]
These are looking great.
