### ISSUE TITLE
Map zoom bug

### ISSUE THREAD

**Issue by pdvorchik** [townhallproject/townHallProject#91]
![image](https://cloud.githubusercontent.com/assets/4419203/23829095/5fb2ec34-06b5-11e7-8e53-6f9de3182976.png)

To reproduce:
Click "submit an event" then once the new panel loads click the navbar logo.

Checked on firefox and chrome on win 10.

**Comment by meganrm** [comment]
it was because an event got assigned an "undefined" lat and lng.
