### ISSUE TITLE
Auto-archiving of past events?

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/townHallProject#93]
Now that the site isn't removing events that are deleted from the Public google doc, is there a way to automate archival of old events? (So I don't have to manually archive them every day)

Let me know if there's an easier way I'm missing.

**Comment by pdvorchik** [comment]
@nathanmwilliams As long as all of the events have dates (Besides the re-occurring ones) it'd be quite easy to filter them out automatically.

@meganrm is this a field on FB?  If so we could do a chrontab or something.  If not it just seems like something that could be done on the query afterward with a filter?

I'd like to have them still in the db though so in case people bookmark the specific they can check it out even after it's done.

My only concern is we properly do the timezone calcs right so we don't prematurely filter stuff out.  Dunno how reliable getting local timezone is.  Alternative would be just to cheat it and give an extra 24 hrs to the clock and move on.

**Comment by nathanmwilliams** [comment]
Extra 24 hours is totally fine by me. No harm in people seeing events from the day before.

**Comment by meganrm** [comment]
Time zones aren't a problem... the site is in pacific time, and all the events with dates have a time zone, so we can say reliably if something is in the past or not. What is a problem is the repeating events. Some of them have dates, but also are repeats. Some have no dates. So the reason I didn't auto archive is I don't want to accidentally archive something that is both in the past but also occurring in the future. Once we are submitting events fully through the form, we can just have a rule that says "archive if in the past, unless it's a repeating event."

**Comment by nathanmwilliams** [comment]
This sounds good to me. No problem to manually archive the recurring events when it's occasionally necessary.

**Comment by meganrm** [comment]
Set up to run once a night at midnight pacific time
