### ISSUE TITLE
Adjusting timezones based on location

### ISSUE THREAD

**Issue by arjavrawal** [townhallproject/townHallProject#96]
Currently it looks like the site's only in Pacific Time. What do we think of possibly having the location sensor adjust the timezone automatically depending on the location?

Using the location sensor also might be able to help us automatically figure out if their rep/senator is holding a townhall near them without them having to input any information.

**Comment by meganrm** [comment]
I'm not sure what you mean by the site is in Pacific time. The events are all in their respective local time, and show their time zone. Can you elaborate?
